inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor'
    - 'config/environments/*.rb'
    - 'bin/*'

Rails:
  Enabled: true

Layout/IndentationConsistency:
  EnforcedStyle: rails
