version: '3'
services:
  redis:
    image: 'redis'
    ports:
      - 127.0.0.1:6379:6379
  postgres:
    image: 'postgres:10.5-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 127.0.0.1:5434:5432
  dependencies:
    image: busybox
    depends_on:
      - redis
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=app
      - POSTGRES_HOST=postgres
      - REDIS_URL=redis://redis
